import type { Guide } from "./types";
import { check, h2, h3, note, ol, p, table, tyler, ul } from "./_helpers";
import { tb } from "../toolkitBlocks";

export const guide: Guide = {
  slug: "freshman-internship-timeline",
  title: "The complete freshman internship timeline: what to do each quarter",
  excerpt: "Most students find out how early recruiting starts when it's already too late. Here's what freshman year, sophomore year, and the start of junior year should actually look like, by track.",
  oneLine: "What to do each quarter of freshman and sophomore year, by track.",
  category: "Getting started",
  date: "2026-09-21",
  author: "Tyler Ho",
  downloads: [],
  related: ["resume-with-zero-experience", "target-list-of-50", "externships"],
  reviewedByTyler: true,
  body: [
    p("The most common thing I hear from sophomores is some version of: \"I didn't know it started this early.\" For finance and consulting especially, and for a growing share of tech and marketing roles, the students who land internships in sophomore and junior summer started building toward them in freshman year. Not by applying to everything they could find, but by doing a few boring things consistently, every week, for a long time."),
    p("This guide is the timeline I give every first-year student. It covers what to do each quarter of freshman year, what changes in sophomore year, and how the calendar differs across Finance, Consulting, Marketing, and Tech. At the end there's a checklist you can print."),
    note("Dates move", "Recruiting timelines move earlier almost every year, and they differ from firm to firm. Treat everything here as a planning map. For any firm you care about, check its careers page for the real dates and put them on your calendar the day you find them."),

    h2("Why freshman year matters more than people think"),
    p("Recruiting doesn't reward the smartest student. It rewards the most persistent one: the student who sent the 40th email, followed up on time, and practiced their stories out loud. Persistence compounds. A student who starts in freshman fall has three or four quarters of relationships, reps, and resume lines by the time the big junior-summer processes open. A student who starts in sophomore spring is trying to do all of that at once, while everyone else is doing it too."),
    p("The other reason freshman year matters: it's the lowest-pressure time you'll ever have to be bad at this. Your first emails will be too long. Your first calls will be stiff. Your first interview will have a moment where your mind goes blank. Better that happens when the stakes are an early-insight program or a local internship than when it's the role you've wanted for two years."),
    p("Here's what matters, in order. Most students study for recruiting in exactly the reverse order."),
    tb.fiveThings(),

    h2("Freshman fall: build the foundation"),
    p("Fall is about getting your materials and your head in order. You're not trying to land anything yet. You're building the things every future conversation will depend on."),
    h3("Write resume v1"),
    p("Write a one-page resume, even if it's thin. High school leadership, jobs, and projects count right now; nobody expects a freshman to have a finance internship. What they do expect is a clean page with specific bullets. Rewrite every bullet from a duty (\"responsible for social media\") into an outcome (\"grew the club's Instagram from 300 to 1,100 followers in one quarter\"). Our resume guide goes line by line."),
    h3("Answer the 25 self-questions"),
    p("Before you can tell good stories in interviews, you need raw material. The 25 self-questions ask things like \"What's something you did that nobody asked you to do?\" and \"When did you fail at something that mattered to you?\" Answer them honestly, in bullet points. Don't try to make anything sound impressive. You'll turn the best answers into 8 behavioral stories later in the year."),
    h3("Pick a direction, not a destination"),
    p("You don't need to know whether you want investment banking or product management. You need one or two directions to explore, so your outreach has a focus. If you're torn, pick the one you'd be happiest talking about for 20 minutes with a stranger. You can switch after ten calls; you'll know a lot more by then."),
    h3("Record your 60-second intro"),
    p("Record yourself answering \"tell me about yourself.\" Watch it. It will be uncomfortable. That's the point. The structure is simple: where you're from, what pulled you into this field, what you've done so far, and why you're talking to this person. In our program, this Week 1 recording is played again at the end, next to the new one. Keep yours."),
    check("Freshman fall checklist",
      "Resume v1, one page, every bullet an outcome",
      "All 25 self-questions answered",
      "One or two directions chosen",
      "LinkedIn set up with a real photo and a clear headline",
      "60-second intro recorded and saved",
    ),

    h2("Freshman winter: start talking to people"),
    p("Winter is when the real work starts. Networking is ranked first for a reason: most early opportunities start with someone who replied to an email and remembered the call, not with an application portal."),
    h3("Build a target list of 50, with names"),
    p("Build a list of 50 companies in your field, each with a named person you're going to email. Tier them. A is dream firms, where you're building relationships for later. B is realistic: boutiques, middle-market firms, local firms, and startups, where most first-year opportunities actually come from. C is safe: places very likely to take a first-year student. Roughly 10 A, 30 B, and 10 C works for most students."),
    h3("Set up your outreach system"),
    p("Sending 50 personalized emails a week sounds impossible until you have a system. Use AI to research people and draft first lines, a mail-merge or sequencing tool to send and follow up, and your own eyes to read every single email before it goes. The AI outreach guide walks through the setup."),
    h3("Hit a weekly number"),
    p("Aim for a steady weekly number, not a burst. In our program the minimum is 50 new sequenced emails a week, every follow-up due that week, and the tracker updated by Sunday night. Ten weeks of that is 500+ emails. You don't need to start at 50, but you do need a number you hit every single week."),
    h3("Turn replies into calls"),
    p("Every reply is a chance at a 20-minute call. Open with \"anything exciting going on lately?\", listen 80% of the time, and send a thank-you note within two hours that mentions one specific thing they said. Log every call in your tracker."),
    h3("Apply to early programs"),
    p("Winter is also when many freshman and sophomore programs take applications: early-insight days, diversity programs, and local internships. They're structured for first-years, so they're worth the application even if you're not sure about the field yet."),
    check("Freshman winter checklist",
      "Target list of 50 companies with named contacts",
      "Outreach system live (sequence + follow-ups)",
      "A weekly email number you hit every week",
      "Every call thanked within 2 hours and logged",
      "Applications in for early programs you qualify for",
    ),

    h2("Freshman spring: turn conversations into opportunities"),
    p("By spring you should have had several calls. Spring is about converting those relationships into introductions, and getting ready to interview."),
    h3("Use the referral close"),
    p("Never ask for a referral directly. At the end of a good call, ask: \"Is there anyone on the team you'd be comfortable introducing me to?\" or \"Is there another perspective you think would be good for me to hear?\" It gives people an easy way to help, and it's how one call becomes three."),
    h3("Stay warm"),
    p("Follow up with the people you spoke to in winter. Share something you learned or did because of their advice. Most relationships die from silence, not rejection."),
    h3("Write and record 8 stories"),
    p("Turn your best self-question answers into 8 behavioral stories. Choose them for uniqueness, not impressiveness. Structure each one as situation, what you did, what changed, what you learned. Then map each story to the questions it can answer: leadership, failure, conflict, teamwork, initiative, and why this field."),
    h3("Say yes to the small internship"),
    p("A first role at a local firm, a startup, or a campus office makes the second role much easier. So does an externship or a scoped project with a real deliverable. The goal of freshman summer is something real you can talk about in an interview."),
    check("Freshman spring checklist",
      "The referral close used on every call",
      "An update sent to everyone whose advice you used",
      "8 stories written, recorded, and mapped",
      "Applications to every open role on your list",
      "A summer plan: internship, job, externship, or project",
    ),

    h2("Freshman summer and sophomore year"),
    p("Freshman summer is for doing something you can talk about, keeping 10–15 relationships warm, and starting technicals for your track. Sophomore year is when the pace picks up: sophomore internships, and in finance and consulting, many of the processes that decide junior summer."),
    p("The good news: if you did freshman year right, sophomore year isn't a new project. It's the same weekly habits, with more relationships behind them and better stories."),
    tb.calendarByQuarter(),

    h2("How the timeline differs by track"),
    p("The quarterly plan above works for everyone, but the pressure points differ. Here's the general shape by track."),
    tb.calendarByTrack(),
    h3("Finance"),
    p("Finance is the earliest. Many junior-summer processes open during sophomore year, and the students who do well have been networking since freshman year. Freshman goals: resume, target list, calls, early-insight and diversity programs. Start technicals in the order accounting, valuation, enterprise vs. equity value, M&A, then LBOs."),
    h3("Consulting"),
    p("Most junior-summer consulting recruiting runs in the fall and winter of junior year, with some sophomore programs earlier. Case interviews are a skill that takes months of practice out loud, so start casing with a partner in sophomore year at the latest."),
    h3("Marketing"),
    p("Marketing timelines are more rolling. Many roles post in winter and spring, and smaller agencies and startups hire when they need someone. Build two portfolio pieces (a campaign idea and an analysis) so you're ready when a role posts."),
    h3("Tech"),
    p("Many tech internships post in late summer and fall for the following summer, and referrals matter a lot. Freshman goals: one strong project you can explain end to end, steady coding practice, and relationships with engineers and product people who can refer you."),

    h2("The weekly rhythm that makes it work"),
    p("A timeline is only useful if something happens every week. This is the rhythm we run in the program, and it works just as well on your own if you're honest with yourself about the numbers."),
    table("One week, the First Offer way", ["When", "What"], [
      ["Monday", "Send this week's new sequenced emails (the program minimum is 50)."],
      ["Tuesday–Thursday", "Calls, thank-you notes within 2 hours, follow-ups due."],
      ["Any day", "One hour on the skill of the moment: resume, stories, the why, technicals."],
      ["Sunday night", "Update your tracker. Read your numbers: sent, replies, calls, level."],
    ]),
    tyler("Two missed weeks in a row is where searches die. If you miss a week, next week's number doesn't go down. You make it up."),

    h2("Common mistakes"),
    ul(
      "Waiting until the resume is perfect before emailing anyone. Good enough and sent beats perfect and saved.",
      "Only targeting famous firms. Your B tier is where most first-year opportunities come from.",
      "Treating calls like interviews. The biggest failure mode on a call is being dry.",
      "Asking for a referral on the first call. Use the close instead.",
      "Tracking everyone you email. Only track people who reply; everyone else lives in the sequence.",
      "Stopping after the first rejection. Recruiting rewards the student who keeps going.",
    ),

    h2("Your next step"),
    ol(
      "Write down next month's targets: emails, calls, and one skill to build.",
      "Put the next three deadlines you know of on your calendar.",
      "Block one hour this week to start your target list.",
    ),
    p("None of this is secret, and it's all free. The hard part is doing it every week. If you want someone checking the work and holding your student to a number, that's exactly what the 12-week program is for."),
  ],
};
